type metaCurrencyType = {
  region: string;
  regionCode: string;
  currencyName: string;
  currencyCode: string;
  flagUrl: string;
};

export const metaCurrency: metaCurrencyType[] = [
  {
    region: 'United Arab Emirates',
    regionCode: 'AE',
    currencyName: 'Dirham',
    currencyCode: 'AED',
    flagUrl: 'https://flagcdn.com/w80/ae.png',
  },
  {
    region: 'Afghanistan',
    regionCode: 'AF',
    currencyName: 'Afghani',
    currencyCode: 'AFN',
    flagUrl: 'https://flagcdn.com/w80/af.png',
  },
  {
    region: 'Albania',
    regionCode: 'AL',
    currencyName: 'Lek',
    currencyCode: 'ALL',
    flagUrl: 'https://flagcdn.com/w80/al.png',
  },
  {
    region: 'Armenia',
    regionCode: 'AM',
    currencyName: 'Dram',
    currencyCode: 'AMD',
    flagUrl: 'https://flagcdn.com/w80/am.png',
  },
  {
    region: 'Netherlands Antilles',
    regionCode: 'AN',
    currencyName: 'Guilder',
    currencyCode: 'ANG',
    flagUrl: 'https://flagcdn.com/w80/an.png',
  },
  {
    region: 'Angola',
    regionCode: 'AO',
    currencyName: 'Kwanza',
    currencyCode: 'AOA',
    flagUrl: 'https://flagcdn.com/w80/ao.png',
  },
  {
    region: 'Argentina',
    regionCode: 'AR',
    currencyName: 'Peso',
    currencyCode: 'ARS',
    flagUrl: 'https://flagcdn.com/w80/ar.png',
  },
  {
    region: 'Australia',
    regionCode: 'AU',
    currencyName: 'Dollar Australia',
    currencyCode: 'AUD',
    flagUrl: 'https://flagcdn.com/w80/au.png',
  },
  {
    region: 'Aruba',
    regionCode: 'AW',
    currencyName: 'Florin',
    currencyCode: 'AWG',
    flagUrl: 'https://flagcdn.com/w80/aw.png',
  },
  {
    region: 'Azerbaijan',
    regionCode: 'AZ',
    currencyName: 'Manat',
    currencyCode: 'AZN',
    flagUrl: 'https://flagcdn.com/w80/az.png',
  },
  {
    region: 'Bosnia and Herzegovina',
    regionCode: 'BA',
    currencyName: 'Convertible Mark',
    currencyCode: 'BAM',
    flagUrl: 'https://flagcdn.com/w80/ba.png',
  },
  {
    region: 'Barbados',
    regionCode: 'BB',
    currencyName: 'Dollar Barbados',
    currencyCode: 'BBD',
    flagUrl: 'https://flagcdn.com/w80/bb.png',
  },
  {
    region: 'Bangladesh',
    regionCode: 'BD',
    currencyName: 'Taka',
    currencyCode: 'BDT',
    flagUrl: 'https://flagcdn.com/w80/bd.png',
  },
  {
    region: 'Bulgaria',
    regionCode: 'BG',
    currencyName: 'Lev',
    currencyCode: 'BGN',
    flagUrl: 'https://flagcdn.com/w80/bg.png',
  },
  {
    region: 'Bahrain',
    regionCode: 'BH',
    currencyName: 'Dinar',
    currencyCode: 'BHD',
    flagUrl: 'https://flagcdn.com/w80/bh.png',
  },
  {
    region: 'Burundi',
    regionCode: 'BI',
    currencyName: 'Franc',
    currencyCode: 'BIF',
    flagUrl: 'https://flagcdn.com/w80/bi.png',
  },
  {
    region: 'Bermuda',
    regionCode: 'BM',
    currencyName: 'Dollar Bermuda',
    currencyCode: 'BMD',
    flagUrl: 'https://flagcdn.com/w80/bm.png',
  },
  {
    region: 'Brunei',
    regionCode: 'BN',
    currencyName: 'Dollar Brunei',
    currencyCode: 'BND',
    flagUrl: 'https://flagcdn.com/w80/bn.png',
  },
  {
    region: 'Bolivia',
    regionCode: 'BO',
    currencyName: 'Boliviano',
    currencyCode: 'BOB',
    flagUrl: 'https://flagcdn.com/w80/bo.png',
  },
  {
    region: 'Brazil',
    regionCode: 'BR',
    currencyName: 'Real',
    currencyCode: 'BRL',
    flagUrl: 'https://flagcdn.com/w80/br.png',
  },
  {
    region: 'Bahamas',
    regionCode: 'BS',
    currencyName: 'Dollar Bahama',
    currencyCode: 'BSD',
    flagUrl: 'https://flagcdn.com/w80/bs.png',
  },
  {
    region: 'Bhutan',
    regionCode: 'BT',
    currencyName: 'Ngultrum',
    currencyCode: 'BTN',
    flagUrl: 'https://flagcdn.com/w80/bt.png',
  },
  {
    region: 'Botswana',
    regionCode: 'BW',
    currencyName: 'Pula',
    currencyCode: 'BWP',
    flagUrl: 'https://flagcdn.com/w80/bw.png',
  },
  {
    region: 'Belarus',
    regionCode: 'BY',
    currencyName: 'Ruble',
    currencyCode: 'BYN',
    flagUrl: 'https://flagcdn.com/w80/by.png',
  },
  {
    region: 'Belize',
    regionCode: 'BZ',
    currencyName: 'Dollar Belize',
    currencyCode: 'BZD',
    flagUrl: 'https://flagcdn.com/w80/bz.png',
  },
  {
    region: 'Canada',
    regionCode: 'CA',
    currencyName: 'Dollar Canada',
    currencyCode: 'CAD',
    flagUrl: 'https://flagcdn.com/w80/ca.png',
  },
  {
    region: 'Congo',
    regionCode: 'CD',
    currencyName: 'Franc',
    currencyCode: 'CDF',
    flagUrl: 'https://flagcdn.com/w80/cd.png',
  },
  {
    region: 'Switzerland',
    regionCode: 'CH',
    currencyName: 'Franc',
    currencyCode: 'CHF',
    flagUrl: 'https://flagcdn.com/w80/ch.png',
  },
  {
    region: 'Chile',
    regionCode: 'CL',
    currencyName: 'Peso',
    currencyCode: 'CLP',
    flagUrl: 'https://flagcdn.com/w80/cl.png',
  },
  {
    region: 'China',
    regionCode: 'CN',
    currencyName: 'Yuan',
    currencyCode: 'CNY',
    flagUrl: 'https://flagcdn.com/w80/cn.png',
  },
  {
    region: 'Colombia',
    regionCode: 'CO',
    currencyName: 'Peso',
    currencyCode: 'COP',
    flagUrl: 'https://flagcdn.com/w80/co.png',
  },
  {
    region: 'Costa Rica',
    regionCode: 'CR',
    currencyName: 'Colon',
    currencyCode: 'CRC',
    flagUrl: 'https://flagcdn.com/w80/cr.png',
  },
  {
    region: 'Cuba',
    regionCode: 'CU',
    currencyName: 'Peso',
    currencyCode: 'CUP',
    flagUrl: 'https://flagcdn.com/w80/cu.png',
  },
  {
    region: 'Czech Republic',
    regionCode: 'CZ',
    currencyName: 'Koruna',
    currencyCode: 'CZK',
    flagUrl: 'https://flagcdn.com/w80/cz.png',
  },
  {
    region: 'Denmark',
    regionCode: 'DK',
    currencyName: 'Krone',
    currencyCode: 'DKK',
    flagUrl: 'https://flagcdn.com/w80/dk.png',
  },
  {
    region: 'Egypt',
    regionCode: 'EG',
    currencyName: 'Pound',
    currencyCode: 'EGP',
    flagUrl: 'https://flagcdn.com/w80/eg.png',
  },
  {
    region: 'Eurozone',
    regionCode: 'EU',
    currencyName: 'Euro',
    currencyCode: 'EUR',
    flagUrl: 'https://flagcdn.com/w80/eu.png',
  },
  {
    region: 'United Kingdom',
    regionCode: 'GB',
    currencyName: 'Pound Sterling',
    currencyCode: 'GBP',
    flagUrl: 'https://flagcdn.com/w80/gb.png',
  },
  {
    region: 'India',
    regionCode: 'IN',
    currencyName: 'Rupee',
    currencyCode: 'INR',
    flagUrl: 'https://flagcdn.com/w80/in.png',
  },
  {
    region: 'Indonesia',
    regionCode: 'ID',
    currencyName: 'Rupiah',
    currencyCode: 'IDR',
    flagUrl: 'https://flagcdn.com/w80/id.png',
  },
  {
    region: 'Japan',
    regionCode: 'JP',
    currencyName: 'Yen',
    currencyCode: 'JPY',
    flagUrl: 'https://flagcdn.com/w80/jp.png',
  },
  {
    region: 'United States',
    regionCode: 'US',
    currencyName: 'US Dollar',
    currencyCode: 'USD',
    flagUrl: 'https://flagcdn.com/w80/us.png',
  },
] as const;
